### PR TITLE
Support tree view drag and drop. 

### PR DESCRIPTION
**Pull request by tsmaeder**
Signed-off-by: Thomas Mäder <t.s.maeder@gmail.com>

#### What it does
Adds support for contributing drag and drop controller in the tree view plugin API. The code tries to mimick the behaviour described in https://code.visualstudio.com/api/references/vscode-api#TreeDragAndDropController&lt;T&gt; as well as possible. I have also refactored some of the "drag into editor area" code to work with the new code (and fixed dragging external files into electron on windows as a "drive-by")

Contributed on behalf of ST Microelectronics

Fixes #11778, Fixes #11776

#### How to test
I have adapted the VS Code tree view sample to exercise the code added in the PR. The extension & source is attached to this PR.
The extension contributes a view called "Test View Drag and Drop", which you need to open.

The example implement multiple features:
1. Drag and drop within the tree
The dropped element should be moved under the element where it was dropped.
Note that there seems to be a bug in our tree-view refresh code where the UI goes into an endless loop when you reparent the elements of the tree: It seems the parent field of the tree items is not properly updated when an item is reparented. I am pretty convinced this is not related to the changes in this PR.
2. Drag an element to the editor area:
This should open a *.js file from the extension itself: note that the cursor will be placed at line 10, column 6.
3. Exercise the current drag and drop to the editor area. Drag from the file navigator and from the OS file explorer
4. Exercise dropping files to the example view: the extension will show the first couple of bytes of the file content.

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by tsmaeder** [comment]
Here's the extension to test:

[custom-view-samples-0.0.1.zip](https://github.com/eclipsesource/theia/files/10368943/custom-view-samples-0.0.1.zip)

and here's the corresponding source:

[tree-view-sample.zip](https://github.com/eclipsesource/theia/files/10368946/tree-view-sample.zip)

**Review by sgraband — COMMENTED** [review]
Thank you for the changes! From testing i have 3 comments/questions:

Minor: The link to the API in the description should be `https://code.visualstudio.com/api/references/vscode-api#TreeDragAndDropController&lt;T&gt;` i believe.

Should i be able to drag a local file into the editor frame in the browser variant? (Does not work for me on Ubuntu 20.04)

Should it be possible to drag a TreeItem to the root of the Tree or is this not supported? (This does also not work for me)

**Comment by tsmaeder** [comment]
> Thank you for the changes! From testing i have 3 comments/questions:
> 
> Minor: The link to the API in the description should be `https://code.visualstudio.com/api/references/vscode-api#TreeDragAndDropController&lt;T&gt;` i believe.
yup

> 
> Should i be able to drag a local file into the editor frame in the browser variant? (Does not work for me on Ubuntu 20.04)
No, I don't think that should work: the editor drop works with URI's and we don't have that from the native DnD API.

> 
> Should it be possible to drag a TreeItem to the root of the Tree or is this not supported? (This does also not work for me)

Not sure, I'll check: by "root" you mean for example dragging to an empty space at the bottom of the view, right?

**Comment by sgraband** [comment]
Yes exactly. Thank you for checking!

**Comment by tsmaeder** [comment]
The VS Code doc says:

> The target tree element that the drop is occurring on. When undefined, the target is the root.

so yes, dragging to an unoccupied area should work. Grr...

**Review by sgraband — APPROVED** [review]
Thank you for the changes! Looks good and works great!

**Comment by tsmaeder** [comment]
Opened https://github.com/eclipse-theia/theia/issues/11778

**Pull request closed without merging**
