### PR TITLE
Add support for "lifecycleManagedByParent"

### PR DESCRIPTION
**Pull request by tsmaeder**
#### What it does
Adds support for the `lifecycleSupportedByParent` flag on debug session. Fixes #11511

#### How to test
* Install built-in javascript debugger plugin with version 1.60.1 (https://open-vsx.org/api/ms-vscode/js-debug/1.61.0/file/ms-vscode.js-debug-1.61.0.vsix). 
* Experiment with auto-attached debug sessions: I used Theia itself for testing: it includes both process with many subprocesses and also the launch.json in the repo contains composite launch configurations
* Make sure terminating debug sessions (root sessions as well as descendant sessions) shows the correct behavior as described in https://code.visualstudio.com/docs/editor/debugging#_compound-launch-configurations and https://code.visualstudio.com/api/references/vscode-api#DebugSessionOptions

Contributed on behalf of ST Microelectronics

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Review by planger — COMMENTED** [review]
Great, thanks! Code looks good to me.

What I've successfully tested is below.
Additionally to that, it may be worth creating a minimal VS Code extension based on [mock-debug](https://github.com/microsoft/vscode-mock-debug) and compare that with how VS Code behaves for the same minimal extension. What do you think @tsmaeder?

## What I've tested

### Setup
* Launch Electron Theia with [ms-vscode.js-debug-1.61.0.vsix](https://open-vsx.org/api/ms-vscode/js-debug/1.61.0/file/ms-vscode.js-debug-1.61.0.vsix)
* Out of Electron Theia start launch configs for browser Theia
* Scenarios below in comparison with VS Code

### Launch Config: Browser backend only (not compound)

#### Theia
* stop -> stops all
* restart -> restarts all

#### VS Code
* stop -> stops all
* restart -> restarts all

### Launch Config: Compound Launch Browser backend and frontend (with `stopAll = false`)

#### Theia
* stop -> stops parent process but not browser
* restart -> restarts parent process but not browser 

#### VS Code
* stop -> stops parent process but not browser
* restart -> restarts parent process but not browser

### Launch Config: Compound Launch Browser backend and frontend (with `stopAll = true`)

#### Theia
* stop -> stops parent process AND browser 
* restart -> restarts parent process but not browser

#### VS Code
* stop -> stops parent process AND browser
* restart -> restarts parent process but not browser

**Comment by tsmaeder** [comment]
> Additionally to that, it may be worth creating a minimal VS Code extension based on [mock-debug](https://github.com/microsoft/vscode-mock-debug) and compare that with how VS Code behaves for the same minimal extension.

I think the only scenario we can't cover with the js-debug extension is the one where there is a process tree where some have the flag `lifecycleManagedByParent` is set for some, but not others: we could check that the propagation of the lifecycle events stops at a process tree root where the flag is not set. Not sure whether that is worth the effort, though.

One bunch of scenarios I didn't see in your testing is when the processes are not terminated by hand, but terminate themselves (for example, killing a subprocess by hand). The lifecycle events should not propagate in this case (if I read the doc correctly).

**Review by planger — APPROVED** [review]
Thanks for the nice work!

**Comment by sdirix** [comment]
Merged upstream with https://github.com/eclipse-theia/theia/pull/11751

**Pull request closed without merging**
