### PR TITLE
Use function calls in prompt templates

### PR DESCRIPTION
**Pull request by lucas-koehler**
#### Parse functions in prompt templates and add to LLM calls

Extends the prompt service to parse function descriptions in format
`~{<id>}` from prompt templates and return them as part of the
resolved prompt.

To support returning tools besides the plain text for resolved prompts, the message signature of `PromptService.getPrompt`
now returns an object of new type ResolvedPromptTemplate.

Similarly, the `getSystemMessage` method of the`AbstractChatAgent` now also return an object.
The `AbstractChatAgent` is adapted to hand over system and
request function descriptions to the LLM.

#### Add highlighting and autocomplete for functions in prompt templates

Extends the prompt template language to add syntax highlighting and
autocompletion for llm functions.

With this, available functions are automatically shown after typing `~{`
and the curly brackets are auto closed.

Implements https://github.com/eclipsesource/osweek-2024/issues/95

### Screencast

[Screencast from 08-13-24 18:37:40.webm](https://github.com/user-attachments/assets/8f78f46f-1851-4e59-9df0-27178e8ccd68)

### How to test

- Edit a prompt template (e.g. of the default agent)
- type `~{`
- available functions should be suggested. Select one or two
- Save the template
- Use the agent and write a prompt that should invoke a tool.

### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by sdirix** [comment]
Works for me! Thanks!

**Comment by JonasHelming** [comment]
@lucas-koehler Did you adapt the prompt template of the workspace agent to use the new format?

**Comment by lucas-koehler** [comment]
@JonasHelming no but that should be quite easy. Should I open a follow up PR for this?

**Comment by JonasHelming** [comment]
yes, please (same ticket)

**Comment by JonasHelming** [comment]
@sdirix Is there any plan how to get these additional PRs into the Theia contribution and when?

**Comment by sdirix** [comment]
I already picked this PR into the contribution. I'm happy to add additional PRs to it until the PR is open.

**Pull request merged**
