### PR TITLE
Improve link handling in markdown for non-existing links

### PR DESCRIPTION
**Pull request by martin-fleck-at**
#### What it does

Fixes https://github.com/eclipsesource/osweek-2024/issues/88

#### How to test

- Enter `[nonexist.ing](file://home/nonexist.ing)` to render a markdown for a non existing link
- Click and see error

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Review by CamilleLetavernier — COMMENTED** [review]
The changes look good to me, and mostly work. However, because the error is now much more prominent, I noticed that the open link error is repeated A LOT of times.

If I ctrl+click on the link for the first time, the error is logged 4 times. If I clear the console and Ctrl+click again, the error is now repeated 9 times. If I clear and click again, it is repeated 19 times. The number of repeats increases every time.

While this behavior can also be observed on the base branch, it is now much more visible, as we're creating a notification every time.

I also wonder if it's a good idea to override the Monaco Editor globally. This feature is not AI-specific and could make sense in the base implementation directly.

**Comment by CamilleLetavernier** [comment]
The repeated error stack:
```
2024-08-01T13:40:14.574Z root ERROR Fail to open 'file://home/nonexist.ing': Error: 'file://home/nonexist.ing' is invalid
    at MonacoEditorProvider.getModel (http://localhost:3000/bundle.js:372823:33)
    at async MonacoEditorProvider.createMonacoEditor (http://localhost:3000/bundle.js:372904:23)
    at async MonacoEditorProvider.doCreateEditor (http://localhost:3000/bundle.js:372842:24)
    at async EditorPreviewWidgetFactory.constructEditor (http://localhost:3000/packages_editor-preview_lib_browser_editor-preview-manager_js.js:253:28)
    at async EditorPreviewWidgetFactory.createEditor (http://localhost:3000/bundle.js:362890:27)
    at async EditorPreviewWidgetFactory.createWidget (http://localhost:3000/packages_editor-preview_lib_browser_editor-preview-manager_js.js:246:24)
    at async WidgetManager.doCreateWidget (http://localhost:3000/bundle.js:341382:24)
    at async AIEditorManager.getOrCreateWidget (http://localhost:3000/bundle.js:361679:24)
    at async AIEditorManager.open (http://localhost:3000/bundle.js:341516:24)
    at async MonacoEditorProvider.interceptOpen (http://localhost:3000/bundle.js:372878:13)
```

**Comment by martin-fleck-at** [comment]
@CamilleLetavernier Thank you for your review, I'll have a look at it right away.

**Comment by martin-fleck-at** [comment]
@CamilleLetavernier I rebased the change to resolve a merge conflict and added a commit to fix the issue. Seems that Theia itself is registering itself way too many times as an opener handler and it gets worse and worse over time. We now only register the opener handler once.

**Review by CamilleLetavernier — APPROVED** [review]
MUCH better, thanks! :tada:

**Pull request merged**
